# Generated by Django 4.2.7 on 2025-11-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('period_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(default='fortnightly', max_length=20)),
                ('has_tanda', models.BooleanField(default=False)),
                ('has_iqb', models.BooleanField(default=False)),
                ('has_journal', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete - Missing Files'), ('uploaded', 'Files Uploaded'), ('reconciling', 'Reconciliation Running'), ('review', 'Under Review - Exceptions Found'), ('approved', 'Approved'), ('posted', 'Posted to Sage Intacct')], default='incomplete', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('Tanda_Timesheet', 'Tanda Timesheet'), ('Micropay_IQB', 'Micropay IQB Report'), ('Micropay_Journal', 'Micropay GL Journal')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('record_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('superseded', 'Superseded by newer version')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='reconciliation.payperiod')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciliation.upload')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TandaTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=20)),
                ('employee_name', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=200)),
                ('team_name', models.CharField(max_length=200)),
                ('award_export_name', models.CharField(max_length=100)),
                ('date_shift_start', models.DateField(blank=True, null=True)),
                ('shift_start_time', models.TimeField(blank=True, null=True)),
                ('date_shift_finish', models.DateField(blank=True, null=True)),
                ('shift_finish_time', models.TimeField(blank=True, null=True)),
                ('shift_hours', models.DecimalField(decimal_places=4, max_digits=8)),
                ('shift_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('is_leave', models.BooleanField(default=False)),
                ('leave_type', models.CharField(blank=True, max_length=50)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanda_records', to='reconciliation.upload')),
            ],
        ),
        migrations.CreateModel(
            name='SageIntacctExport',
            fields=[
                ('export_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('generated', 'Generated - Ready for Upload'), ('uploaded', 'Uploaded to Sage Intacct'), ('posted', 'Posted in Sage Intacct'), ('failed', 'Failed')], default='generated', max_length=20)),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reconciliation.payperiod')),
            ],
            options={
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('total_checks', models.IntegerField(default=0)),
                ('checks_passed', models.IntegerField(default=0)),
                ('checks_failed', models.IntegerField(default=0)),
                ('critical_exceptions', models.IntegerField(default=0)),
                ('warnings', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_runs', to='reconciliation.payperiod')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('recon_type', models.CharField(choices=[('hours', 'Hours Reconciliation: Tanda vs IQB'), ('cost', 'Cost Reconciliation: IQB vs Journal'), ('completeness', 'Completeness Check')], max_length=20)),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=200)),
                ('cost_center', models.CharField(blank=True, max_length=50)),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('variance_pct', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical - Requires Action'), ('warning', 'Warning - Review Recommended'), ('info', 'Information Only')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('accepted', 'Accepted - No Action Required')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('recon_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reconciliation.reconciliationrun')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabourCostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=20)),
                ('employee_name', models.CharField(max_length=200)),
                ('cost_account_code', models.CharField(db_index=True, max_length=50)),
                ('normal_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_leave', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_leave_loading', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sick_leave', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lsl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_leave', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('superannuation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('workcover', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payroll_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_summaries', to='reconciliation.payperiod')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('ledger_account', models.CharField(max_length=20)),
                ('cost_account', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('transaction', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_records', to='reconciliation.upload')),
            ],
        ),
        migrations.CreateModel(
            name='IQBDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('cost_account_code', models.CharField(db_index=True, max_length=50)),
                ('cost_account_description', models.CharField(max_length=200)),
                ('pay_comp_code', models.CharField(max_length=50)),
                ('pay_comp_desc', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(max_length=50)),
                ('hours', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('leave_start_date', models.DateField(blank=True, null=True)),
                ('leave_end_date', models.DateField(blank=True, null=True)),
                ('loading_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iqb_records', to='reconciliation.upload')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionResolution',
            fields=[
                ('resolution_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_message', models.TextField()),
                ('interpreted_action', models.JSONField()),
                ('modification_type', models.CharField(choices=[('note_added', 'Note Added'), ('allocation_changed', 'Cost Allocation Changed'), ('hours_adjusted', 'Hours Adjusted'), ('cost_adjusted', 'Cost Adjusted'), ('employee_reassigned', 'Employee Reassigned'), ('accepted_variance', 'Variance Accepted')], max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(default='pending', max_length=20)),
                ('triggered_rerun', models.BooleanField(default=False)),
                ('rerun_timestamp', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reconciliation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='reconciliation.reconciliationitem')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='CostCenterSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_account', models.CharField(db_index=True, max_length=50)),
                ('target_account', models.CharField(max_length=50)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('source_account', 'target_account')},
            },
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['pay_period', 'source_system', 'is_active'], name='reconciliat_pay_per_6ef731_idx'),
        ),
        migrations.AddIndex(
            model_name='tandatimesheet',
            index=models.Index(fields=['upload', 'employee_id'], name='reconciliat_upload__6071ce_idx'),
        ),
        migrations.AddIndex(
            model_name='tandatimesheet',
            index=models.Index(fields=['location_name'], name='reconciliat_locatio_7ca4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['recon_run', 'status'], name='reconciliat_recon_r_1f4948_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['severity'], name='reconciliat_severit_bf172c_idx'),
        ),
        migrations.AddIndex(
            model_name='labourcostsummary',
            index=models.Index(fields=['pay_period', 'cost_account_code'], name='reconciliat_pay_per_303412_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labourcostsummary',
            unique_together={('pay_period', 'employee_code', 'cost_account_code')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['upload', 'cost_account'], name='reconciliat_upload__0ffe46_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['ledger_account'], name='reconciliat_ledger__44a8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='iqbdetail',
            index=models.Index(fields=['upload', 'employee_code'], name='reconciliat_upload__b97e26_idx'),
        ),
        migrations.AddIndex(
            model_name='iqbdetail',
            index=models.Index(fields=['cost_account_code'], name='reconciliat_cost_ac_8b2b31_idx'),
        ),
        migrations.AddIndex(
            model_name='iqbdetail',
            index=models.Index(fields=['transaction_type'], name='reconciliat_transac_6033af_idx'),
        ),
    ]
