# Generated by Django 4.2.7 on 2025-11-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_alter_payperiod_period_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=20)),
                ('employee_name', models.CharField(max_length=200)),
                ('tanda_total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tanda_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tanda_shift_count', models.IntegerField(default=0)),
                ('tanda_earliest_shift', models.DateTimeField(blank=True, null=True)),
                ('tanda_latest_shift', models.DateTimeField(blank=True, null=True)),
                ('tanda_locations', models.JSONField(default=list)),
                ('tanda_normal_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tanda_leave_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tanda_leave_breakdown', models.JSONField(default=dict)),
                ('iqb_total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iqb_gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iqb_superannuation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iqb_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iqb_normal_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iqb_normal_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iqb_overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iqb_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iqb_annual_leave_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iqb_annual_leave_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iqb_sick_leave_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iqb_sick_leave_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iqb_other_leave_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iqb_other_leave_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_centers', models.JSONField(default=list)),
                ('hours_variance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hours_variance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cost_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_variance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hours_match', models.BooleanField(default=False)),
                ('cost_match', models.BooleanField(default=False)),
                ('has_issues', models.BooleanField(default=False)),
                ('issue_description', models.TextField(blank=True)),
                ('recon_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_recons', to='reconciliation.reconciliationrun')),
            ],
            options={
                'indexes': [models.Index(fields=['recon_run', 'has_issues'], name='reconciliat_recon_r_32825a_idx'), models.Index(fields=['employee_id'], name='reconciliat_employe_3450ef_idx')],
                'unique_together': {('recon_run', 'employee_id')},
            },
        ),
    ]
