# Generated by Django 4.2.7 on 2025-11-22 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_employeereconciliation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeereconciliation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeereconciliation',
            name='pay_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_reconciliations', to='reconciliation.payperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='employeereconciliation',
            unique_together={('pay_period', 'employee_id')},
        ),
        migrations.AddIndex(
            model_name='employeereconciliation',
            index=models.Index(fields=['pay_period', 'has_issues'], name='reconciliat_pay_per_893f99_idx'),
        ),
    ]
