# Generated by Django 4.2.7 on 2025-11-22 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_alter_employeereconciliation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereconciliation',
            name='auto_pay_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeereconciliation',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeereconciliation',
            name='is_salaried',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeereconciliation',
            name='pay_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_reconciliations', to='reconciliation.payperiod'),
        ),
    ]
