# Generated by Django 4.2.7 on 2025-11-22 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0005_employeereconciliation_auto_pay_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_index=True, max_length=200)),
                ('gl_account', models.CharField(blank=True, max_length=20)),
                ('include_in_total_cost', models.BooleanField(default=False)),
                ('is_mapped', models.BooleanField(default=True)),
                ('journal_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('journal_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('journal_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('recon_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_recons', to='reconciliation.reconciliationrun')),
            ],
            options={
                'ordering': ['description'],
                'unique_together': {('recon_run', 'description')},
            },
        ),
    ]
