# Generated by Django 4.2.7 on 2025-11-23 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reconciliation', '0006_journalreconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanda_location', models.CharField(max_length=200, unique=True)),
                ('cost_account_code', models.CharField(max_length=20)),
                ('department_code', models.CharField(max_length=10)),
                ('department_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tanda_location'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentCostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=10)),
                ('department_name', models.CharField(max_length=100)),
                ('gl_account', models.CharField(max_length=20)),
                ('gl_account_name', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee_count', models.IntegerField(default=0)),
                ('cost_center_breakdown', models.JSONField(default=dict)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_summaries', to='reconciliation.payperiod')),
            ],
            options={
                'indexes': [models.Index(fields=['pay_period', 'department_code'], name='reconciliat_pay_per_5838fc_idx')],
                'unique_together': {('pay_period', 'department_code', 'gl_account')},
            },
        ),
        migrations.CreateModel(
            name='CostAllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=20)),
                ('employee_name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('iqb', 'IQB Default'), ('tanda', 'Tanda Timesheet'), ('override', 'Manual Override')], default='iqb', max_length=20)),
                ('allocations', models.JSONField(default=dict)),
                ('total_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_rules', to='reconciliation.payperiod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['pay_period', 'source'], name='reconciliat_pay_per_08aa24_idx'), models.Index(fields=['employee_code'], name='reconciliat_employe_1b9d57_idx')],
                'unique_together': {('pay_period', 'employee_code')},
            },
        ),
    ]
