# Generated by Django 4.2.7 on 2025-11-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0007_locationmapping_departmentcostsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperiod',
            name='has_cost_allocation',
            field=models.BooleanField(default=False),
        ),
    ]
