# Generated by Django 4.2.7 on 2025-11-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0008_payperiod_has_cost_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SageDepartment',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200)),
                ('parent_id', models.CharField(blank=True, max_length=10)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('manager', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['department_id'],
            },
        ),
        migrations.CreateModel(
            name='SageLocation',
            fields=[
                ('location_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('parent_id', models.CharField(blank=True, max_length=10)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('manager', models.CharField(blank=True, max_length=200)),
                ('parent_entity', models.CharField(blank=True, max_length=10)),
                ('entity_base_currency', models.CharField(default='AUD', max_length=10)),
            ],
            options={
                'ordering': ['location_id'],
            },
        ),
    ]
