# Generated by Django 4.2.7 on 2025-11-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0009_sagedepartment_sagelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCompCodeMapping',
            fields=[
                ('pay_comp_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gl_account', models.CharField(max_length=20)),
                ('gl_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['pay_comp_code'],
            },
        ),
    ]
