# Generated by Django 4.2.7 on 2025-11-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0010_paycompcodemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=10)),
                ('location_name', models.CharField(max_length=200)),
                ('department_id', models.CharField(max_length=10)),
                ('department_name', models.CharField(max_length=200)),
                ('cost_account_code', models.CharField(max_length=20)),
                ('gl_account', models.CharField(max_length=20)),
                ('gl_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employee_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_allocations', to='reconciliation.payperiod')),
            ],
            options={
                'ordering': ['location_id', 'department_id', 'gl_account'],
                'indexes': [models.Index(fields=['pay_period', 'location_id'], name='reconciliat_pay_per_3edc76_idx'), models.Index(fields=['pay_period', 'department_id'], name='reconciliat_pay_per_6532a2_idx'), models.Index(fields=['pay_period', 'gl_account'], name='reconciliat_pay_per_249ce7_idx')],
                'unique_together': {('pay_period', 'cost_account_code', 'gl_account')},
            },
        ),
    ]
