# Generated by Django 4.2.7 on 2025-11-29 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0012_validationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayPeriodSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=200)),
                ('location_id', models.CharField(max_length=10)),
                ('location_name', models.CharField(max_length=200)),
                ('department_id', models.CharField(max_length=10)),
                ('department_name', models.CharField(max_length=200)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gl_breakdown', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_snapshots', to='reconciliation.payperiod')),
            ],
            options={
                'ordering': ['employee_code', 'location_id', 'department_id'],
                'indexes': [models.Index(fields=['pay_period', 'employee_code'], name='reconciliat_pay_per_036ae8_idx'), models.Index(fields=['pay_period', 'location_id'], name='reconciliat_pay_per_2120b5_idx'), models.Index(fields=['pay_period', 'department_id'], name='reconciliat_pay_per_3bf75b_idx')],
                'unique_together': {('pay_period', 'employee_code', 'location_id', 'department_id')},
            },
        ),
    ]
