# Generated by Django 4.2.7 on 2025-11-29 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reconciliation', '0013_employeepayperiodsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeepayperiodsnapshot',
            options={'ordering': ['-pay_period__period_end', 'employee_code'], 'verbose_name': 'Employee Pay Period Snapshot', 'verbose_name_plural': 'Employee Pay Period Snapshots'},
        ),
        migrations.RemoveIndex(
            model_name='employeepayperiodsnapshot',
            name='reconciliat_pay_per_2120b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeepayperiodsnapshot',
            name='reconciliat_pay_per_3bf75b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='employeepayperiodsnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='al_closing_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='al_closing_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='allocation_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='allocation_finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='allocation_source',
            field=models.CharField(default='iqb', max_length=20),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='cost_allocation',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2310_annual_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6345_salaries',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6355_sick_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6370_superannuation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6372_toil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='lsl_closing_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='lsl_closing_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='toil_closing_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='toil_closing_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeepayperiodsnapshot',
            name='employee_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='employeepayperiodsnapshot',
            unique_together={('pay_period', 'employee_code')},
        ),
        migrations.AddIndex(
            model_name='employeepayperiodsnapshot',
            index=models.Index(fields=['employee_code', 'pay_period'], name='reconciliat_employe_28d591_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepayperiodsnapshot',
            index=models.Index(fields=['termination_date'], name='reconciliat_termina_375fda_idx'),
        ),
        migrations.RemoveField(
            model_name='employeepayperiodsnapshot',
            name='allocation_percentage',
        ),
        migrations.RemoveField(
            model_name='employeepayperiodsnapshot',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='employeepayperiodsnapshot',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='employeepayperiodsnapshot',
            name='gl_breakdown',
        ),
        migrations.RemoveField(
            model_name='employeepayperiodsnapshot',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='employeepayperiodsnapshot',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='employeepayperiodsnapshot',
            name='source',
        ),
        migrations.RemoveField(
            model_name='employeepayperiodsnapshot',
            name='total_amount',
        ),
    ]
