# Generated by Django 4.2.7 on 2025-11-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0014_alter_employeepayperiodsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2317_long_service_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2318_toil_liability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2320_sick_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6302',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6305',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6309',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6310',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6312',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6315',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6325',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6330',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6331',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6332',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6335',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6338',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6340',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6350',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6375',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6380',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
