# Generated by Django 4.2.7 on 2025-11-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0015_employeepayperiodsnapshot_gl_2317_long_service_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2321_paid_parental',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2325_leasing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2330_long_service_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2350_net_wages',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2351_other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2360_payg_withholding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2391_super_sal_sacrifice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
