# Generated by Django 4.2.7 on 2025-12-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0016_add_missing_gl_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tandatimesheet',
            name='gl_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
