# Generated by Django 4.2.7 on 2025-12-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0017_add_gl_code_to_tanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='source_system',
            field=models.CharField(choices=[('Tanda_Timesheet', 'Tanda Timesheet'), ('Micropay_IQB', 'Micropay IQB Report'), ('Micropay_Journal', 'Micropay GL Journal'), ('Micropay_IQB_Leave', 'Micropay IQB Leave Balance')], max_length=50),
        ),
        migrations.CreateModel(
            name='IQBLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('leave_type', models.CharField(db_index=True, max_length=100)),
                ('leave_description', models.CharField(blank=True, max_length=200)),
                ('balance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('as_of_date', models.DateField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance_records', to='reconciliation.upload')),
            ],
            options={
                'indexes': [models.Index(fields=['upload', 'employee_code', 'leave_type'], name='reconciliat_upload__241c49_idx'), models.Index(fields=['as_of_date', 'leave_type'], name='reconciliat_as_of_d_cd4f54_idx')],
            },
        ),
    ]
