# Generated by Django 4.2.7 on 2025-12-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0018_add_iqb_leave_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqbleavebalance',
            name='leave_loading',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
