# Generated by Django 4.2.7 on 2025-12-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0019_add_leave_loading_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Casual', 'Casual'), ('Contract', 'Contract')], default='Full Time', max_length=50)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended')], default='Active', max_length=50)),
                ('is_salaried', models.BooleanField(default=False, help_text='True if employee receives auto pay (salaried)')),
                ('location', models.CharField(blank=True, help_text='Primary location/cost center', max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('manager', models.CharField(blank=True, max_length=200)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, help_text='Annual salary or hourly rate', max_digits=12)),
                ('pay_rate_type', models.CharField(choices=[('annual', 'Annual Salary'), ('hourly', 'Hourly Rate')], default='annual', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['surname', 'first_name'],
                'indexes': [models.Index(fields=['employment_status'], name='reconciliat_employm_48e5f7_idx'), models.Index(fields=['employment_type'], name='reconciliat_employm_27fc73_idx'), models.Index(fields=['location'], name='reconciliat_locatio_cb639c_idx')],
            },
        ),
    ]
