# Generated by Django 4.2.7 on 2025-12-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0019_add_leave_loading_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Employee Code')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('employment_type', models.CharField(blank=True, max_length=50, verbose_name='Employment Type')),
                ('date_hired', models.DateField(blank=True, null=True, verbose_name='Date Hired')),
                ('pay_point', models.CharField(blank=True, max_length=100, verbose_name='Pay Point')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Termination Date')),
                ('job_classification', models.CharField(blank=True, max_length=200, verbose_name='Job Classification')),
                ('auto_pay', models.CharField(blank=True, max_length=10, verbose_name='Auto Pay')),
                ('normal_hours_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Normal Hours Paid')),
                ('yearly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Yearly Salary')),
                ('auto_pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Auto Pay Amount')),
                ('award_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Award Rate')),
                ('pay_class_description', models.CharField(blank=True, max_length=200, verbose_name='Pay Class Description')),
                ('normal_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Normal Rate')),
                ('default_cost_account', models.CharField(blank=True, max_length=50, verbose_name='Default Cost Account')),
                ('default_cost_account_description', models.CharField(blank=True, max_length=200, verbose_name='Default Cost Account Description')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_type'], name='reconciliat_employm_f07ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['location'], name='reconciliat_locatio_4c8c87_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['termination_date'], name='reconciliat_termina_65e8b7_idx'),
        ),
    ]
