# Generated by Django 4.2.7 on 2025-12-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0020_auto_20251225_1401'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employee',
            new_name='reconciliat_employm_27fc73_idx',
            old_name='reconciliat_employm_f07ac4_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='reconciliat_locatio_cb639c_idx',
            old_name='reconciliat_locatio_4c8c87_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='reconciliat_termina_ac2732_idx',
            old_name='reconciliat_termina_65e8b7_idx',
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_annual_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_base_wages',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_days_in_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_employee_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_payroll_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_superannuation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_workcover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
