# Generated by Django 4.2.7 on 2025-12-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0021_rename_reconciliat_employm_f07ac4_idx_reconciliat_employm_27fc73_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_2055_accrued_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='gl_6300',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
