# Generated by Django 4.2.7 on 2025-12-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0022_employeepayperiodsnapshot_gl_2055_accrued_expenses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQBTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100, unique=True, verbose_name='Transaction Type')),
                ('include_in_hours', models.BooleanField(default=False, verbose_name='Include in Hours')),
                ('include_in_costs', models.BooleanField(default=False, verbose_name='Include in Costs')),
                ('notes', models.TextField(blank=True, help_text='Description or notes about this transaction type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IQB Transaction Type',
                'verbose_name_plural': 'IQB Transaction Types',
                'ordering': ['transaction_type'],
            },
        ),
    ]
