# Generated by Django 4.2.7 on 2025-12-30 04:54

from django.db import migrations
import os
import csv


def populate_transaction_types(apps, schema_editor):
    """Load transaction types from CSV file"""
    IQBTransactionType = apps.get_model('reconciliation', 'IQBTransactionType')

    # Path to CSV file
    csv_path = os.path.join('data', 'iqb_transaction_types.csv')

    if not os.path.exists(csv_path):
        print(f"Warning: CSV file not found at {csv_path}")
        return

    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            transaction_type = row['Transaction Type'].strip()
            include_in_hours = row['Include in Hours'].strip().lower() == 'yes'
            include_in_costs = row['Include in Costs'].strip().lower() == 'yes'
            notes = row.get('Notes', '').strip()

            IQBTransactionType.objects.create(
                transaction_type=transaction_type,
                include_in_hours=include_in_hours,
                include_in_costs=include_in_costs,
                notes=notes,
                is_active=True
            )
            print(f"Created: {transaction_type} (Hours: {include_in_hours}, Costs: {include_in_costs})")


def reverse_populate(apps, schema_editor):
    """Remove all transaction types"""
    IQBTransactionType = apps.get_model('reconciliation', 'IQBTransactionType')
    IQBTransactionType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0023_iqbtransactiontype'),
    ]

    operations = [
        migrations.RunPython(populate_transaction_types, reverse_populate),
    ]
