# Generated by Django 4.2.7 on 2025-12-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0024_populate_iqb_transaction_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_long_service_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayperiodsnapshot',
            name='accrual_toil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
