# Generated by Django 4.2.7 on 2026-01-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0025_add_leave_accrual_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSLProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_from', models.DecimalField(decimal_places=2, help_text='Years of service from (inclusive)', max_digits=5)),
                ('years_to', models.DecimalField(decimal_places=2, help_text='Years of service to (inclusive)', max_digits=5)),
                ('probability', models.DecimalField(decimal_places=4, help_text='Probability (0.0000 to 1.0000)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LSL Probability',
                'verbose_name_plural': 'LSL Probabilities',
                'ordering': ['years_from'],
            },
        ),
        migrations.AddField(
            model_name='iqbleavebalance',
            name='years_of_service',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
