# Generated by Django 4.2.7 on 2026-01-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0026_lslprobability_iqbleavebalance_years_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(choices=[('QLD', 'Queensland'), ('VIC', 'Victoria'), ('NSW', 'New South Wales')], default='QLD', max_length=3, verbose_name='State'),
        ),
    ]
