# Generated by Django 4.2.7 on 2026-01-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0027_employee_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalDescriptionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Description')),
                ('gl_account', models.CharField(max_length=20, verbose_name='GL Account')),
                ('include_in_total_cost', models.BooleanField(default=False, help_text='Y = Include in total labour cost calculations', verbose_name='Include in Total Cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Description Mapping',
                'verbose_name_plural': 'Journal Description Mappings',
                'ordering': ['description'],
            },
        ),
    ]
