# Generated by Django 4.2.7 on 2026-01-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0029_iqbdetailv2'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqbdetailv2',
            name='department_code',
            field=models.CharField(blank=True, help_text="Mapped from cost account code (e.g., '50' from '421-5000')", max_length=10),
        ),
        migrations.AddField(
            model_name='iqbdetailv2',
            name='department_name',
            field=models.CharField(blank=True, help_text="Mapped department name or 'Invalid' if not found", max_length=200),
        ),
        migrations.AddField(
            model_name='iqbdetailv2',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original CSV file name for tracking', max_length=255),
        ),
        migrations.AddField(
            model_name='iqbdetailv2',
            name='include_in_costs',
            field=models.BooleanField(default=False, help_text='Mapped from IQB Transaction Type - whether to include in cost calculations'),
        ),
        migrations.AddField(
            model_name='iqbdetailv2',
            name='location_id',
            field=models.CharField(blank=True, help_text="Mapped from cost account code (e.g., '421' from '421-5000')", max_length=10),
        ),
        migrations.AddField(
            model_name='iqbdetailv2',
            name='location_name',
            field=models.CharField(blank=True, help_text="Mapped location name or 'Invalid' if not found", max_length=200),
        ),
        migrations.AddField(
            model_name='iqbdetailv2',
            name='period_start_date',
            field=models.DateField(blank=True, help_text='Period start date (Period End Date - 13 days, editable)', null=True),
        ),
        migrations.AlterField(
            model_name='iqbdetailv2',
            name='period_end_date',
            field=models.DateField(db_index=True, help_text='Period end date from CSV - determines which month this falls under'),
        ),
        migrations.AddIndex(
            model_name='iqbdetailv2',
            index=models.Index(fields=['file_name'], name='reconciliat_file_na_c52690_idx'),
        ),
        migrations.AddIndex(
            model_name='iqbdetailv2',
            index=models.Index(fields=['location_id', 'department_code'], name='reconciliat_locatio_5c3ed9_idx'),
        ),
    ]
