# Generated by Django 4.2.7 on 2026-01-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0030_iqbdetailv2_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperiod',
            name='process_type',
            field=models.CharField(choices=[('actual_pay_period', 'Actual Pay Period Process'), ('leave_calculation', 'Leave Calculation'), ('monthly_accrual', 'Monthly Accrual'), ('accrual_reversal', 'Monthly Accrual Reversal'), ('payroll_tax_wc', 'Payroll Tax & Workcover')], default='actual_pay_period', help_text='Type of payroll process for this period', max_length=30),
        ),
        migrations.AddField(
            model_name='payperiod',
            name='total_payroll_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total actual payroll cost for the month', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payperiod',
            name='workcover_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.384, help_text='Workcover percentage', max_digits=5, null=True),
        ),
    ]
