# Generated by Django 4.2.7 on 2026-01-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0031_payperiod_process_type_payperiod_total_payroll_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paycompcodemapping',
            options={'ordering': ['pay_comp_code'], 'verbose_name': 'Pay Comp Code Mapping', 'verbose_name_plural': 'Pay Comp Code Mappings'},
        ),
        migrations.AddField(
            model_name='paycompcodemapping',
            name='pay_comp_desc',
            field=models.CharField(blank=True, help_text='Description of the pay component', max_length=200, verbose_name='Pay Comp/Add Ded Desc'),
        ),
        migrations.AddField(
            model_name='paycompcodemapping',
            name='prt_category',
            field=models.CharField(blank=True, help_text='Payroll Tax category for this pay component', max_length=100, verbose_name='PRT - Categories'),
        ),
        migrations.AddField(
            model_name='paycompcodemapping',
            name='transaction_type',
            field=models.CharField(blank=True, help_text='Type of transaction (e.g., Hours By Rate, Super, etc.)', max_length=100, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='paycompcodemapping',
            name='gl_account',
            field=models.CharField(max_length=20, verbose_name='GL ACCOUNT'),
        ),
        migrations.AlterField(
            model_name='paycompcodemapping',
            name='gl_name',
            field=models.CharField(max_length=200, verbose_name='GL NAME'),
        ),
        migrations.AlterField(
            model_name='paycompcodemapping',
            name='pay_comp_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='PAY COMP CODE'),
        ),
    ]
